[package]
name = "aoc_2018"
version = "0.1.0"
authors = ["Nathan Wiebe Neufeldt <wn.nathan@gmail.com>"]

[dependencies]

[[bin]]
name = "01a"
path = "src/01a.rs"

[[bin]]
name = "01b"
path = "src/01b.rs"

[[bin]]
name = "02a"
path = "src/02a.rs"

[[bin]]
name = "02b"
path = "src/02b.rs"
